version: "3"
services:
  xbeach-preparation:
    image: dc7598bc556c
    volumes:
      - ./:/data
    command: xbeach-mi-prepare config.json
  xbeach-orchestrator:
    image: dc7598bc556c
    depends_on:
      - stat
      - instat
    environment:
      - PORT=53603
    volumes:
      - ./:/data
  stat:
    image: deltares/xbeach
    depends_on:
      - xbeach-preparation
    environment:
      - PORT=53606
    volumes:
      - .stat/:/data
  instat:
    image: deltares/xbeach
    depends_on:
      - xbeach-preparation
    environment:
      - PORT=53609
    volumes:
      - .instat/:/data
